### ISSUE TITLE
$TASK_ID's Postprocess makes impact on the whole message. "lowercase" option breaks property replacement.

### ISSUE THREAD

**Issue by Tanatcu** [EugeneKozhun/commit-message-template#30] opened 2024-07-09 16:45 UTC
Today I've found this plugin and fall in love. It's what I were looking for so long time.
But upon configuration I've faced a couple of issues.

Specs:
- OS: MacOS
- WebStorm version: 2024.1.5

Issues:
1. When I select anything except 'Nope' in `Postprocess` dropdown for `$TASK_ID` property, it's being applied on the whole message template (see the attached video).
2. When I select `lowercase` option in `Postprocess` dropdown for `$TASK_ID` property, it breaks replacement for all the properties, that are used in message template (see the attached video).

https://github.com/EugeneKozhun/commit-message-template/assets/15380811/3cb4e26f-4774-43ca-be97-aab64656a1fe

**Comment by EugeneKozhun** [comment] 2024-07-10 06:29
@Tanatcu Hi, thank you so much for the feedback, it's very important to me :D

1) You are right, this is a development issue and it will be fixed in the next release.

2) I couldn't reproduce this behavior on my end.
Could you send me the name of the branch where you are experiencing this issue?

**Comment by EugeneKozhun** [comment] 2024-07-12 13:20
This bug was fixed in version 1.8.1.

Thank you for reporting the problem!

**Closed by EugeneKozhun** 2024-07-12 13:20 UTC
Labels: bug
